version: "2"
services:
  zookeeper:
    image: wurstmeister/zookeeper:latest
    container_name: bootiful-dress-zookeeper
    ports:
      - 2181:2181

  kafka:
    image: wurstmeister/kafka:latest
    container_name: bootiful-dress-kafka
    ports:
      - 9092:9092
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=kafka
      - KAFKA_ADVERTISED_PORT=9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CREATE_TOPICS=dresses:1:1,ratings:1:1
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    depends_on:
      - zookeeper

  postgresdb:
    container_name: bootiful-dress-datastore
    image: postgres:9.6.3
    ports:
         - "5432:5432"
    environment:
         - POSTGRES_USER=postgres
         - POSTGRES_PASSWORD=demo
    command: postgres

  dress-service:
    container_name: bootiful-dress-service
    build: build/docker
    image: cristinatech/spring-cloud-stream-kafka
    depends_on: # baking services will be started before the bootiful-dress-service
      - postgresdb
      - kafka
    ports:
      - "9000:9000"
      - "8081:8081"
      - "5005:5005"
    links:
      - postgresdb
    environment: # docker run -e "SPRING_PROFILES_ACTIVE=docker -e "JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,address=5005,server=y,suspend=n" -p 9000:9000 -p 8081:8081 -p 5005:5005 -t cristinatech/spring-cloud-stream-kafka
      - SPRING_PROFILES_ACTIVE=docker
      - JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,address=5005